myproject/core/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name='core'
urlpatterns =[
    path('start/<category>/',start,name='start'),
    path('createFund/',create_fundraiser,name='create'),
    path('login/',sign_in,name='sign_in'),
    path('logout/',logout_page,name='logout'),
    path('register/',sign_up,name='sign_up'),
    path('reset/',reset_password,name='reset'),
    path('send/',send_email,name='send'),
    path('fundme/<id>/',showFundDetails,name='show'),
    path('donate/<id>/',donate,name='donate'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('reset_password/',
        auth_views.PasswordResetView.as_view(template_name="password-forget.html"),
        name='reset_password'),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=staticfiles_urlpatterns()

myproject/core/models.py
from django.db import models
from django.contrib.auth.models import User
class fundRaised(models.Model):
    username=models.ForeignKey(User,on_delete=models.CASCADE)
    category=models.CharField(max_length=29,choices=[('medical','medical'),('emergency','emergency'),('Education','Education'),('startUps','startUps'),('charity','charity')],default='charity')
    fund_for=models.CharField(max_length=29,choices=[('someoneElse','someoneElse'),('yourself','yourself'),('charity','charity')],default='yourself')
    goal=models.IntegerField(default=0)
    photo=models.ImageField(upload_to='stories/')
    title=models.TextField(max_length=50,unique=True)
    story=models.TextField(max_length=1000)
    present_fund=models.IntegerField(default=0)
    NoDonations=models.IntegerField(default=0)
    withdrawAmount=models.IntegerField(default=0)
    phone=models.TextField()
    def __str__(self):
        return self.title
class Donations(models.Model):
    funds=models.ForeignKey(fundRaised,on_delete=models.CASCADE)
    user=models.ForeignKey(User,null=True,on_delete=models.CASCADE)
    amount=models.IntegerField(default=0)
    comment=models.TextField(max_length=1000)
    paymentMethod=models.CharField(max_length=30)
    def __str__(self):
        return self.funds.title+"--"+str(self.pk)
class successStories(models.Model):
    funds=models.ForeignKey(fundRaised,on_delete=models.CASCADE)
    iv=models.FileField(upload_to='stories/')
    def __str__(self):
        return self.title

myproject/core/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout

def sign_in(request):
    if request.method=='POST':
        email=request.POST['mail']
        password=request.POST['password']
        user=authenticate(username=email,password=password)
        if user is not None:
            login(request,user)
            print(user.username)
            return redirect('/index/')
    return render(request,'sign-in.html')

def logout_page(request):
    logout(request)
    return redirect('/login/')

def sign_up(request):
    if request.method=='POST':
        lastname=request.POST['lastName']
        firstname=request.POST['firstName']
        email=request.POST['email']
        password=request.POST['password']
        confirmpassword=request.POST['confirmPassword']
        if password is not confirmpassword:
            redirect('/login/')
        user=User.objects.create_user(first_name=firstname,last_name=lastname,email=email,password=password,username=email)
        user.save()
    return render(request,'sign-up.html')

def reset_password(request):
    if request.method=="POST":
        mail=request.POST['mail']
        send_email(mail)
        return redirect('/login/')
    return render(request,'password-forget.html')

def start(request,category=None):
    return render(request,'sign-up.html')



from django.core.mail import send_mail
from django.conf import settings
def send_email(mail):
    subject = 'Hello from Django'
    message = 'This is a test email sent from Django.'
    send_mail(subject, message, 'settings.EMAIL_HOST_USER', [mail],fail_silently=False)


@login_required(login_url="/login/")
def create_fundraiser(request):
    if request.method == 'POST':
        data=request.POST
        username=request.user
        category=data.get('category')
        fund_for=data.get('type')
        goal=data.get('amount')
        photo=request.FILES.get('formFile')
        title=data.get('title')
        story=data.get('story')
        phone=data.get('phone')
        fundraiser = fundRaised.objects.create(username=username,category=category,fund_for=fund_for,goal=goal,photo=photo,title=title,story=story,phone=phone)
        return redirect('/login/')
    return render(request, 'donation.html')
    
def showFundDetails(request,id):
    if request.method=='GET':
        f=fundRaised.objects.get(pk=id)
        percent_covered=(f.present_fund/f.goal)*100
        context={'f':f,'percent':percent_covered}
        return render(request,'showDetails.html',context=context)

def donate(request,id):
    if request.method=='POST':
        pass
    return render(request,'donate.html')


myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FundRaiser</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
{% load static %}
<style>
    
    .dropdown:hover .dropdown-menu {
        display: block;
    }
body{
    background-image: url("{% static 'bg.png' %}");
}
.accordion-button:not(.collapsed) {
            background-color: #007bff;
            color: #fff;
        }

        .accordion-button:not(.collapsed)::after {
            display: none;
        }
</style>
</head>
{% load static %}
<body >
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <a class="navbar-brand" href="#"><img src="{% static 'logo.png' %}"></a>
        <div class="container-fluid">
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Category
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'core:start' category='medical' %}">Medical</a></li>
                    <li><a class="dropdown-item" href="{% url 'core:start' category='emergency' %}">Emergency</a></li>
                    <li><a class="dropdown-item" href="{% url 'core:start' category='Education' %}">Education</a></li>
                    <li><a class="dropdown-item" href="{% url 'core:start' category='startUps' %}">Start-up</a></li>
                    <li><a class="dropdown-item" href="{% url 'core:start' category='charity' %}">Charities</a></li>
                </ul>
            </div>
            {% if request.user.is_authenticated %}

      <a href="{% url 'core:logout' %}" class="link-opacity-50-hover link-underline-light" type="submit">logout</a>
      <p>{{request.user.username}}</p>
        {% else %}
        <a href="{% url 'core:sign_in' %}" class="link-opacity-50-hover link-underline-light" type="submit">LogIn</a>
        {% endif %}
            <div class="lg"><a class="link-opacity-50-hover link-underline-light" href="{% url 'core:send' %}">raise fund</a></div>
        </div>
    </div>      <form class="d-flex" role="search">
          <button class="btn btn-outline-primary" type="submit">Search</button>
        </form>

</nav>
<div  style="margin-left: 5%;margin-right: 5%;">
    {% block start %}
    {% endblock %}
</div>
</body>
</html>

myproject/templates/donate.html
{% extends 'base.html' %}
{% block start %}
<div class="row">
<div class="col-md-3"></div>
<div class="col-md-6">

  <div class="card" style="width: 38rem;">
    <div class="card-body">
      <h5 class="card-title">Donation Form</h5>
      <p class="card-text">
        <form>
          <div class="form-group">
            <label for="donationAmount">Enter your donation</label><br><br>
            <input type="text" class="form-control" id="donationAmount" placeholder="0.00" aria-label=" Donation amount"><br>
            <small id="donationHelp" class="form-text text-muted">Please enter a donation amount more than Rs.500</small>
          </div>
          
          
        </form>
      </p>
    </div>
  </div>
  </div>
  <div class="col-md-3"></div>
</div>
{% endblock %}

myproject/templates/donation.html
{% extends 'base.html'%}
{%  block start %}
<div class="container">
    <h1 class="text-center">Donation Form</h1>
    <form class="mt-7 w-50 mx-auto" id="create-fundraiser-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}      

        <div class="mb-3">
            <label for="category">Category</label><br><br>
            <select class="form-control" name="category">
                <option value="charity">Charity</option>
                <option value="medical">Medical</option>
                <option value="education">Education</option>
                <option value="emergency">Emergency</option>
                <option value="startup">Startup</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="type">Who are you fundraising for?</label><br><br>
            <select class="form-control" name="type">
            <option value="yourself">Yourself</option>
                <option value="someone_else">Someone Else</option>
                <option value="charity">Charity</option>
            </select>
        </div><br>
        <div class="mb-3">
            <input type="number" class="form-control" name="amount" placeholder="You starting Goal..">
        </div>
        <div class="mb-3">
            <label for="formFile" class="form-label">Add a cover photo or video</label><br><br>
            <input class="form-control" type="file" name="formFile">
          </div><br>
          <div class="mb-3">
            <input type="text" class="form-control" name="title" placeholder="Enter a Title for Fund">
        </div><br>
        <div class="mb-3">
            <textarea class="form-control" name="story" rows="4" placeholder="Tell your Story.."></textarea>
        </div><br>
        <div class="mb-3">
            <input type="text" class="form-control" name="phone" placeholder="Phone Number">
        </div><br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

myproject/templates/password-forget.html
{% extends 'base.html'%}
{%  block start %}
<div class="container-fluid">
    <p class="text-center">Enter your email address. We'll send you instructions to reset your password</p>
    <form class="mt-5 w-50 mx-auto" method='POST' enctype="multipart/form-data">
      {% csrf_token %}      
      <div class="form-group">
        <input type="email" class="form-control" name="mail" placeholder="Enter email" required>
      </div><br>
      <button type="submit" class="btn btn-primary btn-block">Request password reset</button>
    </form>
  </div>
{% endblock %}

myproject/templates/showDetails.html
{% extends 'base.html'%}
{% block start %}
<div class="row">

    <div class="col-md-8">
        <div class="card w-80" >
            <h3 class="w-80 text-center" >{{f.title}}"</h3> 
            <img class="card-image w-50 h-20" style="margin-left: 25%;margin-top: 2%;margin-bottom: 5%;" src="/media/{{f.photo}}">
        <div class="card-body " >
            <div class="">{{f.username}} is organising this fund</div><hr>
            <div id="accordionExample" class="accordion" style="margin-top: 2rem;">
                <div class="accordion-item">
                    <div>
                        {% if story_length < 400 %}
                        <div class="accordion-body">
                            {{f.story}}
                        </div>
                        {% else %}
                        <span >{{f.story|slice:"0:400"}}</span>
                        <span  id="collapseOne" class="accordion-collapse collapse hide" data-bs-parent="#accordionExample">{{f.story|slice:"400:"}}</span>
                    </div>
                    <h2 class="accordion-header">    
                        <a class="btn btn-outline-secondary"  data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Read More
                        </a>
                    </h2>
                    {% endif %}
                </div>
            </div><hr>
        </div>
    </div>
    </div>
    <div class="col-md-4">
        <div class="card w-100"  >
            <div class="card-body">
            <div class="row">
                <div class="col-md-12" >
                    <p class="mb-3"><span class="text-success">{{f.present_fund}} </span> out of {{f.goal}}</p>
                    <div class="progress mb-3" role="progressbar"  aria-valuenow="5" aria-valuemin="0" aria-valuemax="100" style="height: 5px;">
                        <div class="progress-bar w-{{percent}} bg-success" ></div>
                    </div>
                    <div>
                        <a href="#" class="btn btn-primary">Donate now</a>
                        <a href="#" class="btn btn-outline-success">Share</a>
                    </div><br>
                    <p class="card-text text-primary "> {{f.NoDonations}} people just donated</p>
                    <p class="card-text text-success ">Top Donors</p>
                    <ul style="list-style: None;">
                        <li><div> username : 15$</div></li>
                        <li><div> username : 11$</div></li>
                        <li><div> username : 10$</div></li>
                    </ul>
                    <a href="#" class="btn btn-outline-secondary w-100">See all</a>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

myproject/templates/sign-in.html
{% extends 'base.html'%}
{% block start %}
    <div class="container-fluid">
      <h1 class="text-center">Sign In to FundRaiser</h1>
      <h3 class="text-center" style="color:red;">Be Kind Be Happy</h3>
        <form class="mt-5 w-50 mx-auto" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <input type="email" class="form-control" name="mail" placeholder="Enter email" required>
        </div><br>
        <div class="form-group">
          <input type="password" class="form-control" name="password" placeholder="Enter password" required>
        </div><br>
        <button type="submit" class="btn btn-primary btn-block">Sign In</button>
      </form>
      <div class="text-center mt-3">
        <a href="{% url 'core:reset' %}">Forgot your password?</a>
      </div>
      <div class="text-center mt-3">
        <a href="{% url 'core:sign_up' %}" class="text-primary">Don't have an account? Sign up</a>
      </div>
    </div>
{% endblock %}

myproject/templates/sign-up.html
{% extends 'base.html'%}
{% block start %}
<div class="container-fluid">
    <h1 class="text-center">Welcome to GoFundMe</h1>
    <h2 class="text-center">Create an account</h2>
    <form class="mt-5 w-50 mx-auto" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        <input type="text" class="form-control" name="firstName" placeholder="Enter first name">
      </div><br>
      <div class="form-group">
        <input type="text" class="form-control" name="lastName" placeholder="Enter last name">
      </div><br>
      <div class="form-group">
        <input type="email" class="form-control" name="email" placeholder="Enter email">
      </div><br>
      <div class="form-group">
        <input type="password" class="form-control" name="password" placeholder="Enter password">
      </div><br>
      <div class="form-group">
        <input type="password" class="form-control" name="confirmPassword" placeholder="Confirm Password">
      </div><br>
      <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
    </form>
    <div class="text-center mt-3">
      <a href="{% url 'core:sign_in' %}" class="text-primary">Already have an account? Sign in</a>
    </div>
    <div class="text-center mt-3">
      <p>By clicking the Sign Up button below, you agree to the GoFundMe <a href="#" class="text-primary">Terms of Service</a> and acknowledge the Privacy Notice.</p>
    </div>
  </div>
{% endblock %}